# name of the workflow
name: Java CI with Gradle
# section that defines events
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    # we can define like new contributor, or when an issue is created something like that
    # https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows
# workflows
jobs:
  build:

    runs-on: ubuntu-latest
    
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v2
    # this checkout command can be found on github it's another yaml file v4 means version 4
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1 # the version of java we don't need to download it like in Jenkis, select an action
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
      

